version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Ayaka
  - bumpp
  - colorette
  - guiiai
  - localetime
  - Logg
  - moeru
  - Neko
  - unbird
ignoreWords: []
import: []
