name: Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Existing release tag to publish
        required: true
        type: string
  push:
    tags:
      - 'v*'

concurrency: ${{ github.workflow }}-${{ inputs.tag || github.ref_name }}

jobs:
  publish:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag && format('refs/tags/{0}', inputs.tag) || github.ref }}
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: latest
          registry-url: https://registry.npmjs.org

      # npm 11.5.1 or later is required so update to latest to use OIDC trusted publisher
      # https://github.com/eslint/config-inspector/pull/174/files
      # https://github.com/e18e/ecosystem-issues/issues/201
      - run: npm install -g npm@latest
      - run: pnpm install --frozen-lockfile
      - run: pnpm dlx changelogithub
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm run build
      - run: npm publish --access public --dry-run
      - run: npm publish --access public
